import streamlit as st
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table
from reportlab.lib.styles import getSampleStyleSheet
import plotly.io as pio
import pandas as pd
import tempfile, os

st.title('PDF Report Generator')

file = st.file_uploader('Upload MCP CSV/Excel for report', type=['csv','xls','xlsx'])

if file:
    df=None
    try:
        from utils.csv_validator import validate_and_standardize
        df = validate_and_standardize(file)
    except Exception as e:
        st.error(f'Validation error: {e}')

    if df is not None:
        st.write('Generating report preview...')
        # create a small forecast chart image
        fig = None
        try:
            from utils.plot_helpers import plot_last_7days
            fig = plot_last_7days(df)
            tmp = tempfile.NamedTemporaryFile(delete=False, suffix='.png')
            pio.write_image(fig, tmp.name, format='png', scale=2)
            tmp.close()
        except Exception as e:
            tmp = None

        if st.button('Generate PDF'):
            path = 'bess_report.pdf'
            styles = getSampleStyleSheet()
            doc = SimpleDocTemplate(path, pagesize=A4)
            story = []
            logo_path = 'frontend/assets/dvc_logo.png' if os.path.exists('frontend/assets/dvc_logo.png') else None
            story.append(Paragraph('BESS Optimiser Report', styles['Title']))
            story.append(Spacer(1,12))
            story.append(Paragraph('Executive summary: Generated by BESS Optimiser', styles['BodyText']))
            story.append(Spacer(1,12))
            if tmp is not None:
                story.append(RLImage(tmp.name, width=400, height=200))
                story.append(Spacer(1,12))
            # simple table from head
            tbl_data = [list(df.columns[:5])] + df.head(10).fillna('').astype(str).values.tolist()
            try:
                story.append(Table(tbl_data))
            except Exception:
                pass
            doc.build(story)
            with open(path,'rb') as f:
                st.download_button('Download PDF Report', f, file_name='bess_report.pdf')
